artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  aws_access_id: your aws access id
  aws_secrete_key: your aaws secrete key
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  bucket_name: your s3 bucket name
  data_filename: which dataset you want to download from your s3 bucket



data_preprocessing:
  training_org_img_folder: artifacts/data_ingestion/images/Training_original
  training_segment_img_folder: artifacts/data_ingestion/images/Training_segment
  testing_org_img_folder: artifacts/data_ingestion/images/Test_original
  testing_segment_img_folder: artifacts/data_ingestion/images/Test_segment


model_callback:
  root_dir: artifacts/segmentation_model
  model_save_path: artifacts/segmentation_model/base_model.h5
  

model_training:
  root_dir: artifacts/segmentation_model
  base_model: artifacts/segmentation_model/base_model.h5


model_evaluation:
  model_path: artifacts/segmentation_model/base_model.h5
  training_org_img_folder: artifacts/data_ingestion/images/Training_original
  training_segment_img_folder: artifacts/data_ingestion/images/Training_segment
  testing_org_img_folder: artifacts/data_ingestion/images/Test_original
  testing_segment_img_folder: artifacts/data_ingestion/images/Test_segment



